/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-09-27 02:53:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.swing.JOptionPane;

public final class editar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.swing.JOptionPane");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style/styles.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style/main.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1 class=\"titulo-tienda\">Editar usuario</h1>\r\n");
      out.write("	\r\n");
      out.write("	");

		int cedula = Integer.parseInt(request.getParameter("cedula"));
		Class.forName("com.mysql.jdbc.Driver");
		Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/tienda","root", "Julian0992");
		PreparedStatement ps = conexion.prepareStatement("SELECT * FROM usuarios WHERE cedula_usuario = "+cedula);
		ResultSet result = ps.executeQuery();
		while(result.next()){
		
      out.write("\r\n");
      out.write("	<section class=\"main\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<section class=\"row\">\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"border-top border-bottom py-3\">\r\n");
      out.write("						<p class=\"ingresa\">Ingresa los datos a modificar</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<br>\r\n");
      out.write("					<div>\r\n");
      out.write("						<form action=\"\" method = \"post\">\r\n");
      out.write("							<label for=\"cedula2\">\r\n");
      out.write("								<span>Cedula:</span>\r\n");
      out.write("								<input type = \"text\" name = \"cedula2\" id =\"cedula2\" value=\"");
      out.print( result.getInt("cedula_usuario") );
      out.write("\">\r\n");
      out.write("							</label>\r\n");
      out.write("							<label for=\"correo\">\r\n");
      out.write("								<span>Correo:</spanl>\r\n");
      out.write("								<input type = \"text\" name = \"correo\" id=\"correo\" value=\"");
      out.print( result.getString("email_usuario") );
      out.write("\">\r\n");
      out.write("							</label>\r\n");
      out.write("							<label for=\"nombre\">\r\n");
      out.write("								<span>Nombre:</span>\r\n");
      out.write("								<input type = \"text\" name = \"nombre\" id=\"nombre\" value=\"");
      out.print( result.getString("nombre_usuario") );
      out.write("\">\r\n");
      out.write("							</label>\r\n");
      out.write("							<label for=\"pass\">\r\n");
      out.write("								<span>Contraseña:</span>\r\n");
      out.write("								<input type = \"text\" name = \"pass\" id=\"pass\" value=\"");
      out.print( result.getString("password") );
      out.write("\">\r\n");
      out.write("							</label>\r\n");
      out.write("							<label for=\"usuario\">\r\n");
      out.write("								<span>Usuario:</span>\r\n");
      out.write("								<input type = \"text\" name = \"usuario\" id=\"usuario\" value=\"");
      out.print( result.getString("usuario") );
      out.write("\">\r\n");
      out.write("							</label>\r\n");
      out.write("							<div class=\"contenedor-botones\">\r\n");
      out.write("								<input type=\"submit\" value=\"Editar\" class=\"botones-usuario\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("					");
} 
					//int cedula2 = Integer.parseInt(request.getParameter("cedula2"));
					String correo = request.getParameter("correo");
					String nombre = request.getParameter("nombre");
					String pass = request.getParameter("pass");
					String usuario = request.getParameter("usuario");
					
					if (correo != null && nombre != null && pass != null && usuario != null){
						String sql = "UPDATE usuarios SET email_usuario ='"+correo+"', nombre_usuario = '"+nombre+"', password = '"+pass+"', usuario = '"+usuario+"' WHERE cedula_usuario = "+cedula;
						Statement st = conexion.createStatement();
						st.executeUpdate(sql);
						JOptionPane.showMessageDialog(null, "Datos del Usuario Borrados");
						response.sendRedirect("usuarios.jsp");
					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
